# tmuxinator
export EDITOR=nvim

#move configpath for lazygit/lazydocker to .config
export XDG_CONFIG_HOME="$HOME/.config"

# golang
export PATH="$HOME/go/bin:$PATH"

#asdf
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
# append completions to fpath
fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
fpath=(~/.oh-my-zsh/completions $fpath)

# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

### EXPORT INSTALLED PROGRAMS
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
# Я ваще хз что это, но установил т.к через asdf не устанавливался php
# На макос он установлен в /usr/bin/bison 2.3
export PATH="/opt/homebrew/opt/bison/bin:$PATH"
# Add Go to PATH
export PATH="/opt/homebrew/opt/go/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="bureau"

# Auto-update every 7 days
zstyle ':omz:update' frequency 7

# Enable command auto-correction
ENABLE_CORRECTION="false"

# Which plugins would you like to load?
plugins=(
  git
  docker
  docker-compose
  macos
  composer
  kubectl
  history
  zsh-autosuggestions
  dotenv
  gpg-agent
  keychain
 # zsh-vi-mode
)

source $ZSH/oh-my-zsh.sh

# User configuration

### > alias section ###

# Open ObsidianNotes with NeoVim
alias nvnotes='cd ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ObsidianNotes; nvim'
alias mux=tmuxinator

### < alias section ###

# Added by Docker Desktop
source /Users/vladislav/.docker/init-zsh.sh || true


# Enable ngrok completion if installed
if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

# Added with JetBrains crack-script
___my_vmoptions_shell_file="${home}/.jetbrains.vmoptions.sh"; if [ -f "${___my_vmoptions_shell_file}" ]; then . "${___my_vmoptions_shell_file}"; fi


# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
# Set up fuck
eval $(thefuck --alias)
